"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zyl^r389wfj)qx3yh9g(nsqqwm&#(nx^rmj97b6$4%g$im#qrs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['caiogab.pythonanywhere.com', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'colorfield',
    'kb',
    'tinymce',
    'visual.apps.VisualConfig',
    'sigecom_integration',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]



ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'visual.context_processors.site_appearance',
                'core.context_processors.dashboard_charts',
                'core.context_processors.categories_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sbrkb',  # PREENCHA
        'USER': 'postgres',  # PREENCHA
        'PASSWORD': 'pv6g836wj84vx9YW',  # PREENCHA
        'HOST': 'pv6g836wj84vx9YW',  # PREENCHA
        'PORT': '5432',  # PREENCHA
        'OPTIONS': {
            'options': '-c client_encoding=UTF8'
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('en', _('English')),
    ('pt-br', _('Portuguese (Brazil)')),
    ('es', _('Spanish')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "core" / "static",
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media Files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# TinyMCE Configuration
TINYMCE_DEFAULT_CONFIG = {
    'height': 720,
    'width': '100%',
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'theme': 'silver',
    'plugins': ''''
            textcolor save link image media preview codesample contextmenu
            table code lists fullscreen  insertdatetime  nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists  charmap print  hr
            anchor pagebreak
            ''',
    'toolbar1': ''''
            fullscreen preview bold italic underline | fontselect,
            fontsizeselect  | forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | bullist numlist table
            | link image media | codesample | 
            ''',
    'toolbar2': ''''
            visualblocks visualchars |
            charmap hr pagebreak nonbreaking anchor |  code |
            ''',
    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
    'extended_valid_elements': 'iframe[src|width|height|name|align|class|frameborder|allowfullscreen|allow|scrolling|seamless|id]',
    'valid_children': '+body[style]',
}

JAZZMIN_SETTINGS = {
    "site_title": "Admin da KB SistemasBr",
    "site_header": "KB SistemasBr",
    "site_brand": "KB SistemasBr",
    "site_logo": "img/adminlogo.webp",
    "login_logo": "img/adminlogo.webp",
    "welcome_sign": "Bem-vindo ao painel de administração da KB da SistemasBr",
    "copyright": "SistemasBr",
    "topmenu_links": [
        {"name": "Início",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Visualizar Site", "url": "kb:home", "new_window": True},
        {"name": "Base de Conhecimento", "model": "kb.Artigo"},
        {"name": "Avisos Sigecom", "model": "sigecom_integration.Aviso"},
        {
            "name": "Configurações",
            "icon": "fas fa-cogs",
            "children": [
                {"name": "Aparência do Site", "model": "visual.SiteAppearance"},
                {"name": "Aparência do Admin", "model": "visual.AdminAppearance"},
                {"name": "Configurações Operacionais", "model": "core.OperationalSettings"},
            ]
        },
    ],
    "user_avatar": "profile.image",
    "icons": {
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "kb.artigo": "fas fa-newspaper",
        "kb.categoria": "fas fa-sitemap",
        "kb.feedback": "fas fa-comments",
        "visual.adminappearance": "fas fa-cogs",
        "visual.siteappearance": "fas fa-palette",
        "sigecom_integration.aviso": "fas fa-bullhorn",
    },
    "show_ui_builder": True,
    "custom_css": "admin/css/custom_admin.css",

    # Ordenação dos aplicativos na página inicial
    "order_with_respect_to": ["kb", "sigecom_integration", "visual", "core", "auth"],
}

LOGIN_REDIRECT_URL = 'kb:home'
